name: Run node script
description: Runs a Node.js script

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Run script
      run: node index.js
