name: Example Workflow
on:
  push:
    branches:
      - main

jobs:
  run-node-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run custom Node.js Action
        uses: ./ # Caminho para a Action local
      - name: Create .env file with secrets
        run: |
          echo "MY_SECRET_KEY1=${{ secrets.MY_SECRET_KEY }}" >> .env
          echo "MY_SECRET_KEY2=${{ secrets.DB_PASSWORD }}" >> .env
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}