name: Run Node.js Script

on:
  push:
    branches:
      - main

jobs:
  run-node-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Node.js script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REALM: ${{ secrets.REALM }}
          BASE_URL: ${{ secrets.BASE_URL }}
          AUTH_URL: ${{ secrets.AUTH_URL }}
        run: node app/app.js